### ISSUE TITLE
Link dead

### ISSUE THREAD

**Issue by al-sabr** [omega-gg/3rdparty#1]
https://discord.com/channels/705770212485496852/749360800598065282/836143684667179009

**Comment by al-sabr** [comment]
\`\`\`

/cygdrive/g/programming/c++/3rdparty

$ ./generate.sh win64

CLEANING

ARTIFACT 3rdparty-win64

https://dev.azure.com/bunjee/3rdparty/_apis/build/builds/2298/artifacts

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                Dload  Upload   Total   Spent    Left  Speed

100   268  100   268    0     0    268      0  0:00:01 --:--:--  0:00:01   418

DOWNLOADING 3rdparty-win64

curl: no URL specified!

curl: try 'curl --help' for more information

\`\`\`

**Comment by 3unjee** [comment]
Thanks, I'll take a look.

**Comment by 3unjee** [comment]
You're not up to date, do a `git pull`.
